### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by Andie48**
Ok, sorry, here are the files for german translation. My fault.

Greetings

### CODE REVIEW

**Comment by OrionFive** [comment]
Excellent, thank you!

**Comment by OrionFive** [comment]
Hm. You created the pull request on your version of the mod. That won't work. You'll have to do the pull request on mine.

**Comment by OrionFive** [comment]
Make sure you first accept your own pull request or you lose the changes.

**Comment by Andie48** [comment]
Sorry, my first time with github...

**Comment by OrionFive** [comment]
No problem. I'll check if it's good now when I have more time later.

**Pull request merged**
